server:
  port: 8083
spring:
  application:
    name: restTemplate
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/   #注册中⼼的访问地址。
    instance:
      prefer-ip-address: true  #是否将当前服务的 IP 注册到 Eureka Server